### ISSUE TITLE
diego health logs

### ISSUE THREAD

**Issue by mcelep** [cloudfoundry-attic/health_manager#11]
Hi ,

When switching an app to diego, the following logs start getting generated:
2016-01-25 09:48:28 [HEALTH/0] OUT Exit status 0
2016-01-25 09:48:58 [HEALTH/0] OUT healthcheck passed
2016-01-25 09:48:58 [HEALTH/0] OUT Exit status 0
2016-01-25 09:49:28 [HEALTH/0] OUT healthcheck passed
2016-01-25 09:49:28 [HEALTH/0] OUT Exit status 0
2016-01-25 09:49:58 [HEALTH/0] OUT healthcheck passed

These log messages are not necessarily of interest for the end user and they should be excluded from the client log stream.

I've created the same issue on diego repo as I am not sure which team would be the right one, here is the link to the other issue:
https://github.com/cloudfoundry-incubator/diego-release/issues/126

Best Regards,
Murat

**Comment by dieucao** [comment]
Hi Murat,

Thanks for reporting this issue.

I believe the correct repo for this type of issue is 
https://github.com/cloudfoundry-incubator/diego

Also, there's a similar issue against that repo you could take a look at:
https://github.com/cloudfoundry-incubator/diego/issues/1

If the stories linked to iin that issue don't address your concerns, please open an issue against that repo so that the Diego team can see that.

Closing this issue here.
